# PyTextminer global configuration
---
# PyTextMiner will ignore fields absent from the file
fields:
  titleField: 'doc_titl'
  contentField: 'doc_abst'
  authorField: 'doc_acrnm'
  corpusNumberField: 'corp_num'
  docNumberField: 'doc_num'
  index1Field: 'index_1'
  index2Field: 'index_2'
  dateStartField: 'doc_date_start'
  dateEndField: 'doc_date_end'
  keywordsField: 'doc_keywords'
# csv format
delimiter: ','
quotechar: '"'
# application settings
locale: 'en_US.UTF-8'
minSize: 1
maxSize: 4
