---
# application main params
general:
    # where all path and following file are located
    basedirectory: '.'
    locale: ''
    # following directories or files a under "basedirectory"
    index: 'index'
    dbenv: 'db'
    log: 'log'
    loglevel: 'debug'
    user: 'user'
    shared: 'shared'
    source_file_directory: 'source_files'
    userstopwords: 'user_stopwords.csv'
    # stopwords are under share
    stopwords: 'stopwords\en.txt'
# extraction settings
datasets:
    # tina csv columns declaration
    # will ignore undeclared fields
    # and warn not found optional fields
    tinacsv:
        fields:
            titleField: 'doc_titl'
            contentField: 'doc_abst'
            authorField: 'doc_acrnm'
            corpusNumberField: 'corp_id'
            docNumberField: 'doc_id'
            # next fields are optional
            #index1Field: 'doc_index_1'
            #index2Field: 'doc_index_2'
            #dateField: 'doc_date'
            keywordsField: 'doc_keywords'
        # csv reader params
        #delimiter: ','
        #quotechar: '"'
        #encoding: 'utf-8'
    medline:
        period_size: 4
        encoding: 'ascii'
    # extraction params
    ngramMin: 1
    ngramMax: 4
    # tagger learning on 2 x training_tagger_size sentences of tagged nltk corpus
    training_tagger_size: 8000
    # under "basedirectory" directory, delete this file to regenerate a new one on next starting
    tagger: 'shared_tagger.pickle'
    postag_valid: '^((VB.?,|CD.?,|JJ.?,|\?,){0,2}?(N.?,|\?,))+?((PREP.?|DET.?,|IN.?,|CC.?,|\?,)((VB.?,|CD.?,|JJ.?,|\?,){0,2}?(N.?,|\?,))+?)*?$'
    #postag_valid: '^((VB.?,|JJ.?,|\?,){0,2}?(N.?,|\?,))+?((IN.?,|CC.?,|\?,)((VB.?,|JJ.?,|\?,){0,2}?(N.?,|\?,))+?)*?$'
datamining:
    template: 'shared\gexf\gexf.default.template'
    DocumentGraph:
        edgethreshold:
            - 0.0
            - 'inf'
        nodethreshold:
            - 1.0
            - 'inf'
        proximity: 'logJaccard'
    NGramGraph:
        edgethreshold:
            - 0.0
            - 'inf'
        nodethreshold:
            - 1.0
            - 'inf'
        alpha: 0.1
        hapax: 1
        proximity: 'equivalenceIndex'
