---
# application main params
general:
    # where all path and following file are located
    basedirectory: '.'
    locale: ''
    index: 'index'
    dbenv: 'db'
    log: 'log'
    loglevel: 'debug'
    user: 'user'
    shared: 'shared'
    source_file_directory: 'source_files'
    # stopwords are under share
    stopwords: 'stopwords\en.txt'
    userstopwords: 'user_stopwords.csv'
# extraction settings
datasets:
    # tina csv columns declaration
    # will ignore undeclared fields
    # and warn not found optional fields
    tinacsv:
        fields:
            titleField: 'doc_titl'
            contentField: 'doc_abst'
            authorField: 'doc_acrnm'
            corpusNumberField: 'corp_id'
            docNumberField: 'doc_id'
            # next fields are optional
            index1Field: 'doc_index_1'
            index2Field: 'doc_index_2'
            dateField: 'doc_date'
            keywordsField: 'doc_keywords'
        # csv reader params
        delimiter: ','
        quotechar: '"'
        locale: ''
    medline:
        period_size: 4
        locale: ''
    # extraction params
    ngramMin: 1
    ngramMax: 4
    training_tagger_size: 8000
    stemmer: 'tinasoft.pytextminer.stemmer'
    # under "share" directory
    tagger: 'shared/tagger.pickle'
datamining:
    template: 'shared\gexf\gexf.template'
    DocumentGraph:
        edgethreshold:
            - 0.0
            - 'inf'
        nodethreshold:
            - 1
            - 'inf'
        proximity: 'DocumentGraph.inverseLogOccNGrams'
    NGramGraph:
        edgethreshold:
            - 0.0
            - 1.0
        nodethreshold:
            - 1
            - 'inf'
        alpha: 0.1
        proximity: 'NGramGraph.pseudoInclusionProx'
