"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from os.path import join
from glob import glob

from setuptools import setup

APP = ['Tinasoft.py']
DATA_FILES = []

OPTIONS = {
    'argv_emulation': True,
    'argv_inject': "config_unix.yaml",
    'includes': ['tinasoft.data.gexf','tinasoft.data.medline','tinasoft.data.tinasqlite','tinasoft.data.tinacsv','tinasoft.data.whitelist','tinasoft.data.coocmatrix','tinasoft.data.basecsv','traceback','zope.interface','twisted','nltk','numpy','jsonpickle','yaml','tenjin','simplejson','twisted.web','twisted.internet','encodings'],
    'excludes': ['_gtkagg', '_tkagg', 'curses', 'email', 'tcl',
            'Tkconstants', 'Tkinter','tinasoft.data.tinabsddb','bsddb3'],
    'plist': {
        'LSEnvironment': {'NLTK_DATA':'shared/nltk_data'}
    },
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

