"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from os.path import join
from glob import glob

from setuptools import setup

APP = ['Tinasoft.py']
DATA_FILES = [
    ('',glob(r'desktop_config_unix.yaml')),
    ('',glob(r'LICENSE')), 
    ('source_files',glob(join('source_files','*.csv'))),
    ('',glob(join('static'))), 
    (join('shared','gexf'), glob(join('shared','gexf','gexf.template'))),
    (join('shared','stopwords'), glob(join('shared','stopwords','*.txt'))),
    (join('shared','nltk_data','corpora','brown'), glob(join('shared','nltk_data','corpora','brown','*.*'))),
    (join('shared','nltk_data','corpora','conll2000'), glob(join('shared','nltk_data','corpora','conll2000','*.*'))),
    (join('shared','nltk_data','tokenizers','punkt'), glob(join('shared','nltk_data','tokenizers','punkt','*.*')))
]

OPTIONS = {
'argv_emulation': True,
'argv_inject': "desktop_config_unix.yaml",
'includes': ['zope.interface','twisted','nltk','numpy','jsonpickle','yaml','tenjin','simplejson'],
'resources': DATA_FILES
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

