"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from os.path import join
from glob import glob

from setuptools import setup

APP = ['httpserver.py']
DATA_FILES = [
    ('',glob(r'config.yaml')),
    ('',glob(r'LICENSE')),      
    (join('shared','gexf'), glob(join('shared','gexf','gexf.template'))),
    (join('shared','stopwords'), glob(join('shared','stopwords','*.txt'))),
    (join('shared','nltk_data','corpora','brown'), glob(join('shared','nltk_data','corpora','brown','*.*'))),
    (join('shared','nltk_data','corpora','conll2000'), glob(join('shared','nltk_data','corpora','conll2000','*.*'))),
    (join('shared','nltk_data','tokenizers','punkt'), glob(join('shared','nltk_data','tokenizers','punkt','*.*')))
]

OPTIONS = {
'argv_emulation': True,
'includes': ['zope.interface','twisted','nltk','numpy','jsonpickle','yaml','bsddb3','tenjin','simplejson']
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

